### ISSUE TITLE
Leikkuunestejärjestelmä

### ISSUE THREAD

**Issue by PetteriAimonen** [HacklabJKL/sergei_cnc2#12]
Metallien jyrsintä olisi paljon kätevämpää jos käytössä olisi leikkuunesteen automaattinen syöttö.
Vaatisi keruuastiat reunoille pöydältä tippuvaa leikkuunestettä varten.

Sumutus vai virtaava leikkuuneste? (mist vs. flood coolant)

**Comment by PetteriAimonen** [comment]
Keruusysteemi saatu toimivaksi, mutta nestepumppu jumittelee.

**Comment by PetteriAimonen** [comment]
Toiminut nyt ok, nestelinja tyhjenee painovoiman vaikutuksesta kun käyttämättömänä; voisi laittaa jonkin anturoinnin että milloin neste on ehtinyt putkeen saakka.

**Comment by hacklabjkl-cnc-kone** [comment]
Toiminut ihan ok.
